author: Zetaeta
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.zetaeta.settlement.SettlementPlugin
name: Settlement
startup: postworld
version: '0.1'
commands:
    settlement:
        usage: /derp